In [79]:
import pandas as pd
import numpy as np

In [80]:
data=pd.DataFrame({"a":["one","two"]*3,
                   "b":[1,1,2,3,2,3]})
data

a  b
0  one  1
1  two  1
2  one  2
3  two  3
4  one  2
5  two  3

In [81]:
data.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [82]:
data.drop_duplicates()

a  b
0  one  1
1  two  1
2  one  2
3  two  3

In [83]:
data["c"]=range(6)
data

a  b  c
0  one  1  0
1  two  1  1
2  one  2  2
3  two  3  3
4  one  2  4
5  two  3  5

In [84]:
data.duplicated(["a","b"],keep="last")

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [116]:
df=pd.DataFrame({"names":["Tim","tom","Sam",
                          "kate","Kim"],
                "scores":[60,50,70,80,40]})
df

names  scores
0   Tim      60
1   tom      50
2   Sam      70
3  kate      80
4   Kim      40

In [117]:
classes={"Tim":"A","Tom":"A","Sam":"B",
         "Kate":"B","Kim":"B"}

In [118]:
df

names  scores
0   Tim      60
1   tom      50
2   Sam      70
3  kate      80
4   Kim      40

In [121]:
df["names"] = df["names"].str.capitalize()
 
df

names  scores branches
0   Tim      60        A
1   Tom      50        A
2   Sam      70        B
3  Kate      80        B
4   Kim      40        B

In [120]:
df["branches"]=df["names"].map(classes)

In [122]:
df

names  scores branches
0   Tim      60        A
1   Tom      50        A
2   Sam      70        B
3  Kate      80        B
4   Kim      40        B

In [127]:
s=pd.Series([80,70,90,60])
s

0    80
1    70
2    90
3    60
dtype: int64

In [129]:
s.replace(70,np.nan)

0    80.0
1     NaN
2    90.0
3    60.0
dtype: float64

In [130]:
s

0    80
1    70
2    90
3    60
dtype: int64

In [131]:
s.replace([70,60],[np.nan,0])

0    80.0
1     NaN
2    90.0
3     0.0
dtype: float64

In [93]:
s.replace({90:100,60:0})

0     80
1     70
2    100
3      0
dtype: int64

In [94]:
df=pd.DataFrame(
    np.arange(12).reshape(3,4),
    index=[0,1,2],
    columns=["tim","tom","kim","sam"])
df

tim  tom  kim  sam
0    0    1    2    3
1    4    5    6    7
2    8    9   10   11

In [95]:
s=pd.Series(["one","two","three"])
df.index=df.index.map(s)

In [96]:
df

tim  tom  kim  sam
one      0    1    2    3
two      4    5    6    7
three    8    9   10   11

In [97]:
df.rename(index=str.title,columns=str.upper)

TIM  TOM  KIM  SAM
One      0    1    2    3
Two      4    5    6    7
Three    8    9   10   11

In [98]:
df.rename(index={"one":"ten"},
          columns={"sam":"kate"},
          inplace=True)
df

tim  tom  kim  kate
ten      0    1    2     3
two      4    5    6     7
three    8    9   10    11

In [135]:

sc=[30,80,40,90,60,45,95,75,55,100,65,85]
len(sc)

12

In [133]:
x=[20,40,60,80,100]

gives out a categorical output specifying which interval from x does each element from sc lie in

In [101]:
y=pd.cut(sc,x)
y

[(20, 40], (60, 80], (20, 40], (80, 100], (40, 60], ..., (60, 80], (40, 60], (80, 100], (60, 80], (80, 100]]
Length: 12
Categories (4, interval[int64, right]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

gives the index of the bin(category) each element from sc belongs to

In [144]:
y.codes

array([ 0,  3,  1,  3,  2,  1,  3,  2,  1, -1,  2,  3], dtype=int8)

gives a list of all the unique categories the data has been segmented into. Can think of it as a version of cut function with all the duplicates removed

In [145]:
y.categories

IntervalIndex([[20, 40), [40, 60), [60, 80), [80, 100)], dtype='interval[int64, left]')

gives the number of elements in each bin

In [143]:
pd.value_counts(y)

C:\Users\Home\AppData\Local\Temp\ipykernel_19628\3605348509.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(y)


[80, 100)    4
[40, 60)     3
[60, 80)     3
[20, 40)     1
Name: count, dtype: int64

This makes the intervals closed on the left and open on right. i.e includes the first value in the interval and not the last value

In [105]:
y=pd.cut(sc,x,right=False)
y

[[20, 40), [80, 100), [40, 60), [80, 100), [60, 80), ..., [60.0, 80.0), [40.0, 60.0), NaN, [60.0, 80.0), [80.0, 100.0)]
Length: 12
Categories (4, interval[int64, left]): [[20, 40) < [40, 60) < [60, 80) < [80, 100)]

In [106]:
nm=["low", "medium", "high", "very high"]
pd.cut(sc,x,labels=nm)

['low', 'high', 'low', 'very high', 'medium', ..., 'high', 'medium', 'very high', 'high', 'very high']
Length: 12
Categories (4, object): ['low' < 'medium' < 'high' < 'very high']

10 equal intervals are creted between the min and max values of sc

In [107]:
pd.cut(sc,10)

[(29.93, 37.0], (79.0, 86.0], (37.0, 44.0], (86.0, 93.0], (58.0, 65.0], ..., (72.0, 79.0], (51.0, 58.0], (93.0, 100.0], (58.0, 65.0], (79.0, 86.0]]
Length: 12
Categories (10, interval[float64, right]): [(29.93, 37.0] < (37.0, 44.0] < (44.0, 51.0] < (51.0, 58.0] ... (72.0, 79.0] < (79.0, 86.0] < (86.0, 93.0] < (93.0, 100.0]]

divides the data into bins such that each bin contains approximately the same number of observations

In [158]:
data=np.random.randn(100)
c=pd.qcut(data,4)
c

[(0.743, 2.617], (-0.627, 0.0986], (-2.556, -0.627], (0.743, 2.617], (0.0986, 0.743], ..., (-0.627, 0.0986], (-0.627, 0.0986], (0.743, 2.617], (-2.556, -0.627], (0.743, 2.617]]
Length: 100
Categories (4, interval[float64, right]): [(-2.556, -0.627] < (-0.627, 0.0986] < (0.0986, 0.743] < (0.743, 2.617]]

* np.random.randint(4) generates a single random integer from 0 to 3.


* np.random.permutation(4) generates an array with all integers from 0 to 3 in a random order.


In [109]:
rw=np.random.permutation(4)
rw

array([1, 3, 2, 0])

Takes values from the data [(arange(100))] as the indices given by rw

In [110]:
data.take(rw)

array([ 0.38967531, -0.43106941,  1.03205737, -0.25663869])

In [163]:
data=np.random.randn(100).reshape(25,4)

In [164]:
data1 = pd.DataFrame(data)
data1

0         1         2         3
0   1.071854 -1.399685 -0.222838 -0.373712
1  -0.272265  1.308441 -0.430041 -0.624159
2  -1.157383  0.259773  0.232841 -0.427217
3   0.307840  0.545718  0.286897  0.867324
4   0.022296 -0.764925 -0.999109  0.980282
5  -0.981661 -0.433659 -0.180396 -2.206921
6   0.923132 -1.412190  0.549795 -0.094016
7   0.011004 -1.067903 -0.029112 -0.957761
8  -1.430008  1.084956 -1.030137  1.918160
9  -1.581640  1.175599 -0.918895 -0.370871
10 -0.525152  0.350076  0.341670 -1.332565
11  0.570737 -1.600787 -1.613002 -0.025368
12  0.702233 -0.913921 -0.224503  0.607542
13  0.586427  1.744493 -0.017365  1.466393
14 -1.066960 -0.110049  1.788114  0.446906
15 -0.204145 -0.392954  2.196963  1.097919
16  0.020140  0.384006  0.281095 -0.268338
17  1.141122 -1.324945 -0.032446 -1.352451
18 -1.765171 -0.884701  0.249885 -0.204868
19 -1.252843 -3.220388 -0.429430 -0.216889
20 -0.997058  1.652757 -0.923047  0.733472
21 -1.467863 -0.350413 -1.053194 -1.308501
22 -0.357125 -0.157785 -1.317629  0.411380
23 -1.531717 -1.598938  0.082049 -0.530952
24  1.077099  0.648297 -1.503094  0.752092

In [165]:
data1.sample()

0         1         2         3
4  0.022296 -0.764925 -0.999109  0.980282

In [172]:
data1.sample(n=2)

0         1         2         3
10 -0.525152  0.350076  0.341670 -1.332565
13  0.586427  1.744493 -0.017365  1.466393

## Dummy Variable

In [ ]:
data=pd.DataFrame(
    {"letter":["c","b","a","b","b","a"],
                   "number":range(6)})
data

letter  number
0      c       0
1      b       1
2      a       2
3      b       3
4      b       4
5      a       5

creates a new DataFrame (dummy_df) where each unique category in "letter" becomes a new binary (0 or 1) column

In [ ]:
pd.get_dummies(data["letter"])

a  b  c
0  0  0  1
1  0  1  0
2  1  0  0
3  0  1  0
4  0  1  0
5  1  0  0

In [ ]:
data=np.random.randn(10)
data

array([-0.47399816, -0.4700948 , -0.10090975, -0.49105714,  0.85748633,
       -2.17384891, -1.89062041,  1.15155524, -1.12043372,  0.82935199])

In [ ]:
pd.get_dummies(pd.cut(data,4))

(-2.177, -1.342]  (-1.342, -0.511]  (-0.511, 0.32]  (0.32, 1.152]
0                 0                 0               1              0
1                 0                 0               1              0
2                 0                 0               1              0
3                 0                 0               1              0
4                 0                 0               0              1
5                 1                 0               0              0
6                 1                 0               0              0
7                 0                 0               0              1
8                 0                 1               0              0
9                 0                 0               0              1