In [1]:
import numpy as np

In [2]:
arr = np.random.rand(5,5)

### sort an array along a specified axis

In [3]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))   

[[0.00291565 0.10388148 0.12048598 0.04178355 0.00302831]
 [0.11702321 0.17503959 0.21112718 0.53025565 0.0464994 ]
 [0.53725582 0.49380976 0.7492533  0.78708372 0.15379198]
 [0.72313476 0.53158239 0.94291801 0.82932469 0.3530157 ]
 [0.75612406 0.97774886 0.99296845 0.83846543 0.99810309]]


In [4]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.00291565 0.10388148 0.12048598 0.04178355 0.00302831]
 [0.11702321 0.17503959 0.21112718 0.53025565 0.0464994 ]
 [0.53725582 0.49380976 0.7492533  0.78708372 0.15379198]
 [0.72313476 0.53158239 0.94291801 0.82932469 0.3530157 ]
 [0.75612406 0.97774886 0.99296845 0.83846543 0.99810309]]


In [5]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[0.00291565 0.00302831 0.04178355 0.10388148 0.12048598]
 [0.0464994  0.11702321 0.17503959 0.21112718 0.53025565]
 [0.15379198 0.49380976 0.53725582 0.7492533  0.78708372]
 [0.3530157  0.53158239 0.72313476 0.82932469 0.94291801]
 [0.75612406 0.83846543 0.97774886 0.99296845 0.99810309]]


In [6]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[0.00291565 0.00302831 0.04178355 0.10388148 0.12048598]
 [0.0464994  0.11702321 0.17503959 0.21112718 0.53025565]
 [0.15379198 0.49380976 0.53725582 0.7492533  0.78708372]
 [0.3530157  0.53158239 0.72313476 0.82932469 0.94291801]
 [0.75612406 0.83846543 0.97774886 0.99296845 0.99810309]]


### compute the indices that would sort an array along a specified axis

In [7]:
arr = np.random.rand(5,5)

In [8]:
# along the row
print(np.argsort(arr, axis=0))

[[4 3 1 3 2]
 [0 2 4 2 1]
 [1 4 2 0 4]
 [3 1 3 4 0]
 [2 0 0 1 3]]


In [9]:
# along the column
print(np.argsort(arr, axis=1))

[[0 4 2 3 1]
 [2 4 0 1 3]
 [4 2 1 3 0]
 [1 2 3 0 4]
 [0 4 2 1 3]]


In [10]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[ 7 16 14 20  9 24 22 12 17  0 11  5  4 18 21  6 13  2 15 10  3 19 23  8
  1]
