In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

### ```np.concatenate((a, b), axis=0)```

In [3]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [4]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ```np.vstack((a, b))``` 
### ```np.r_[a, b]```

In [5]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [6]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [7]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [8]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split an array 

In [9]:
arr = np.random.rand(6,6)

In [10]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.64689566, 0.11199541, 0.12617237, 0.15810666, 0.50049354,
        0.95180515],
       [0.14199443, 0.6204979 , 0.77527133, 0.49112903, 0.98901769,
        0.39491735],
       [0.94959742, 0.29244747, 0.015551  , 0.83233095, 0.89926168,
        0.84176864]]), array([[0.38776187, 0.93275434, 0.01430882, 0.31067752, 0.76623683,
        0.62484332],
       [0.45882909, 0.02537048, 0.27630682, 0.63340614, 0.06439098,
        0.72977677],
       [0.58852574, 0.59353618, 0.96111053, 0.90291023, 0.95279621,
        0.12841233]])]


In [11]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.64689566, 0.11199541, 0.12617237],
       [0.14199443, 0.6204979 , 0.77527133],
       [0.94959742, 0.29244747, 0.015551  ],
       [0.38776187, 0.93275434, 0.01430882],
       [0.45882909, 0.02537048, 0.27630682],
       [0.58852574, 0.59353618, 0.96111053]]), array([[0.15810666, 0.50049354, 0.95180515],
       [0.49112903, 0.98901769, 0.39491735],
       [0.83233095, 0.89926168, 0.84176864],
       [0.31067752, 0.76623683, 0.62484332],
       [0.63340614, 0.06439098, 0.72977677],
       [0.90291023, 0.95279621, 0.12841233]])]
