In [23]:
import numpy as np

### select the unique elements from an array

In [24]:
arr = np.array([1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6]


In [25]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


### compute the intersection & union of two arrays

In [26]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [27]:
# intersection
print(np.intersect1d(arr1, arr2))

[3 4 5]


In [28]:
# union
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


### compute whether each element of an array is contained in another

In [29]:
print(np.in1d(arr1, arr2))

[False False  True  True  True]


In [30]:
# preserve the shape of the array in the output, if the array is of higher dimensions
print(np.isin(arr1, arr2))

[False False  True  True  True]


### compute the elements in an array that are not in another

In [31]:
print(np.setdiff1d(arr1, arr2))

[1 2]


### compute the elements in either of two arrays, but not both

In [32]:
print(np.setxor1d(arr1, arr2))

[1 2 6 7]


In [33]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

In [34]:
print(arr1.dot(arr2))
# or
print(np.dot(arr1, arr2))
# or
print(arr1 @ arr2)

[[0.77425775 0.92478496 0.9970862  0.77856539 1.01179095]
 [0.83098407 1.00311884 1.18658335 1.2558105  2.01116025]
 [1.07404034 0.94243988 1.32890363 1.37481715 1.77186641]
 [0.28147701 0.26305284 0.66217351 0.69815586 0.7212657 ]
 [0.76935014 1.16682167 0.94266137 0.81566087 1.42279285]]
[[0.77425775 0.92478496 0.9970862  0.77856539 1.01179095]
 [0.83098407 1.00311884 1.18658335 1.2558105  2.01116025]
 [1.07404034 0.94243988 1.32890363 1.37481715 1.77186641]
 [0.28147701 0.26305284 0.66217351 0.69815586 0.7212657 ]
 [0.76935014 1.16682167 0.94266137 0.81566087 1.42279285]]
[[0.77425775 0.92478496 0.9970862  0.77856539 1.01179095]
 [0.83098407 1.00311884 1.18658335 1.2558105  2.01116025]
 [1.07404034 0.94243988 1.32890363 1.37481715 1.77186641]
 [0.28147701 0.26305284 0.66217351 0.69815586 0.7212657 ]
 [0.76935014 1.16682167 0.94266137 0.81566087 1.42279285]]


### QR factorization 

In [35]:
arr = np.random.rand(5,5)

q, r = np.linalg.qr(arr)
print(q)
print(r)

[[-0.45651327  0.55928911  0.65954107  0.19420753 -0.0779765 ]
 [-0.486901   -0.03912209 -0.36394037 -0.1111797  -0.78522822]
 [-0.4903966  -0.41529204 -0.15459941  0.68830098  0.29897238]
 [-0.4703316   0.339338   -0.41640139 -0.45503418  0.53215758]
 [-0.30466771 -0.63090998  0.48503804 -0.51875636  0.06899369]]
[[-1.49112364 -1.27917559 -1.34455294 -1.4042316  -0.64988121]
 [ 0.         -0.59538996 -0.0195952  -0.42177294 -0.33576443]
 [ 0.          0.          0.59364187 -0.10603504 -0.07100378]
 [ 0.          0.          0.         -0.40469398  0.03232002]
 [ 0.          0.          0.          0.          0.10060606]]


### compute eigen values

In [36]:
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr))

[ 2.67422113+0.j          0.38543567+0.65658459j  0.38543567-0.65658459j
 -0.25849421+0.j          0.08327467+0.j        ]


### eigen value decomposition

In [37]:
arr = np.random.rand(5,5)

w, v = np.linalg.eig(arr)
print(w)    # eigen values
print(v)    # eigen vectors

[ 2.91018435+0.j        -0.33659755+0.0892956j -0.33659755-0.0892956j
  0.35434116+0.j         0.07129478+0.j       ]
[[ 0.44969771+0.j         -0.40072624-0.30661426j -0.40072624+0.30661426j
  -0.30735991+0.j         -0.51589677+0.j        ]
 [ 0.47249498+0.j          0.15246201+0.0472271j   0.15246201-0.0472271j
  -0.14655206+0.j         -0.36547402+0.j        ]
 [ 0.42257384+0.j         -0.68965241+0.j         -0.68965241-0.j
   0.05516558+0.j         -0.45503333+0.j        ]
 [ 0.45087825+0.j          0.3498935 -0.08019259j  0.3498935 +0.08019259j
   0.80883268+0.j          0.42344383+0.j        ]
 [ 0.43893123+0.j          0.28292623+0.18816773j  0.28292623-0.18816773j
  -0.47623401+0.j          0.46251405+0.j        ]]


### compute the trace & determinant

In [38]:
# notice this is not a function in linalg!!!
print(np.trace(arr))    


2.6626251978767606


In [39]:
print(np.linalg.det(arr))

0.008915772358665136


### calculate the inverse/psedo-inverse of a matrix

In [40]:
arr = np.random.rand(5,5)

In [41]:
# compute the inverse of a matrix
print(np.linalg.inv(arr))

[[-0.35365157  1.21535763  0.55944683  0.0421794  -0.6917594 ]
 [ 9.34088117 -7.3215421  -2.21138397  0.81660251 -4.78253638]
 [-5.84068391  4.71873105  0.04798976  0.45850454  3.45060887]
 [-4.33725813  2.22383461  1.94632718 -0.03930702  2.36582686]
 [-0.37476192  1.25462108  0.044171   -1.04343814  1.19854586]]


In [42]:
# compute the psudo-inverse of a matrix
print(np.linalg.pinv(arr))

[[-0.35365157  1.21535763  0.55944683  0.0421794  -0.6917594 ]
 [ 9.34088117 -7.3215421  -2.21138397  0.81660251 -4.78253638]
 [-5.84068391  4.71873105  0.04798976  0.45850454  3.45060887]
 [-4.33725813  2.22383461  1.94632718 -0.03930702  2.36582686]
 [-0.37476192  1.25462108  0.044171   -1.04343814  1.19854586]]


### solve a linear system

In [43]:
# solve a linear system in closed form
y = [1,2,3,4,5]
print(np.linalg.solve(arr, y))

[  0.4653248  -32.58262679  22.82781     17.62129886   4.08596998]


In [44]:
# calculate the least-squares solution of a linear system
y = [1,2,3,4,5]
solution, residuals, rank, singular = np.linalg.lstsq(arr, y)
print(solution)
print(residuals)
print(rank)
print(singular)

[  0.4653248  -32.58262679  22.82781     17.62129886   4.08596998]
[]
5
[2.93763487 0.6841422  0.62891507 0.5254785  0.06095237]


C:\Users\Home\AppData\Local\Temp\ipykernel_15140\727852024.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  solution, residuals, rank, singular = np.linalg.lstsq(arr, y)
