# Data Structures 

In [96]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [97]:
import matplotlib.pyplot as plt

In [98]:
A = np.round(10*np.random.rand(5,4))

In [99]:
A

array([[ 0., 10.,  6.,  2.],
       [ 0.,  5.,  1.,  6.],
       [ 8.,  3.,  8.,  2.],
       [ 5.,  2.,  2.,  8.],
       [ 7.,  0.,  7.,  6.]])

In [100]:
A[1,2]

1.0

In [101]:
A[1,:]

array([0., 5., 1., 6.])

In [102]:
A[:,1]

array([10.,  5.,  3.,  2.,  0.])

In [103]:
A[1:3,2:4]

array([[1., 6.],
       [8., 2.]])

In [104]:
A

array([[ 0., 10.,  6.,  2.],
       [ 0.,  5.,  1.,  6.],
       [ 8.,  3.,  8.,  2.],
       [ 5.,  2.,  2.,  8.],
       [ 7.,  0.,  7.,  6.]])

In [105]:
A.T

array([[ 0.,  0.,  8.,  5.,  7.],
       [10.,  5.,  3.,  2.,  0.],
       [ 6.,  1.,  8.,  2.,  7.],
       [ 2.,  6.,  2.,  8.,  6.]])

In [106]:
import numpy.linalg as la

In [107]:
la.inv(np.random.rand(3,3))

array([[-1.96419004,  4.81887664, -3.82247201],
       [-2.35897862, -0.49272186,  2.30725514],
       [ 3.48262342, -2.59064882,  1.41698115]])

In [108]:
A

array([[ 0., 10.,  6.,  2.],
       [ 0.,  5.,  1.,  6.],
       [ 8.,  3.,  8.,  2.],
       [ 5.,  2.,  2.,  8.],
       [ 7.,  0.,  7.,  6.]])

In [109]:
A.sort(axis=0)

In [110]:
A

array([[ 0.,  0.,  1.,  2.],
       [ 0.,  2.,  2.,  2.],
       [ 5.,  3.,  6.,  6.],
       [ 7.,  5.,  7.,  6.],
       [ 8., 10.,  8.,  8.]])

In [111]:
A.sort(axis=1)

In [112]:
A

array([[ 0.,  0.,  1.,  2.],
       [ 0.,  2.,  2.,  2.],
       [ 3.,  5.,  6.,  6.],
       [ 5.,  6.,  7.,  7.],
       [ 8.,  8.,  8., 10.]])

In [113]:
A = np.arange(100)

In [114]:
B = A[[3,5,6]]

In [115]:
B

array([3, 5, 6])

In [116]:
B[0] = -4

In [117]:
B

array([-4,  5,  6])

In [118]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [119]:
B = A[A<40]

In [120]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [121]:
B = A[(A<40) & (A>30)]

In [122]:
B

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [123]:
# &, and 
# |, or
# ~, not

In [124]:
A = np.round(10*np.random.rand(2,3))

In [125]:
A

array([[9., 2., 2.],
       [8., 2., 1.]])

In [126]:
A+3

array([[12.,  5.,  5.],
       [11.,  5.,  4.]])

In [127]:
A+(np.arange(2).reshape(2,1))

array([[9., 2., 2.],
       [9., 3., 2.]])

In [128]:
A

array([[9., 2., 2.],
       [8., 2., 1.]])

In [129]:
B = np.round(10*np.random.rand(2,2))

In [130]:
A

array([[9., 2., 2.],
       [8., 2., 1.]])

In [131]:
B

array([[7., 9.],
       [0., 9.]])

In [132]:
C = np.hstack((A,B))

In [133]:
C

array([[9., 2., 2., 7., 9.],
       [8., 2., 1., 0., 9.]])

In [134]:
A = np.random.permutation(np.arange(10))

In [135]:
A

array([3, 4, 9, 6, 8, 0, 7, 5, 1, 2])

In [136]:
A.sort()

In [137]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
np.sort(A)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
A.sort()

In [140]:
A = A[::-1]

In [141]:
A

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [142]:
A = np.array(["abc",'howare you','u765','13er'])

In [143]:
A.sort()

In [144]:
A

array(['13er', 'abc', 'howare you', 'u765'], dtype='<U10')

In [145]:
B = np.random.rand(1000000)
%timeit sum(B)
%timeit np.sum(B)  # B.sum()

247 ms ± 46.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.82 ms ± 1.62 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [146]:
def mySum(G):
    s = 0
    for x in G:
        s+=x
    return s

In [147]:
import pandas as pd

In [148]:
print(pd.__version__)

2.2.2


In [149]:
A = pd.Series([2,3,4,5],index=['a','b','c','d'])

In [150]:
type(A.values)

numpy.ndarray

In [151]:
type(A)

pandas.core.series.Series

In [152]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [153]:
A['a']

2

In [154]:
A['a':'c']

a    2
b    3
c    4
dtype: int64

In [155]:
grads_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grads = pd.Series(grads_dict)

In [156]:
grads.values

array([4. , 3.5, 3. , 2.5])

In [157]:
marks_dict = {'A':85,'B':75,'C':65,'D':55}
marks = pd.Series(marks_dict)

In [158]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [159]:
marks['A']

85

In [160]:
marks[0:2]

A    85
B    75
dtype: int64

In [161]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [162]:
grads

A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64