In [1]:
import numpy as np

In [2]:
arr = np.random.rand(3,4)

### transpose an array

In [3]:
# the following methods return a copy
print(arr.T)
# or 
print(np.transpose(arr))
# or
print(arr.transpose())

[[0.90971718 0.77175076 0.34980711]
 [0.63521059 0.89323775 0.85417051]
 [0.92260911 0.76695081 0.6151757 ]
 [0.01387662 0.32906322 0.02141629]]
[[0.90971718 0.77175076 0.34980711]
 [0.63521059 0.89323775 0.85417051]
 [0.92260911 0.76695081 0.6151757 ]
 [0.01387662 0.32906322 0.02141629]]
[[0.90971718 0.77175076 0.34980711]
 [0.63521059 0.89323775 0.85417051]
 [0.92260911 0.76695081 0.6151757 ]
 [0.01387662 0.32906322 0.02141629]]


### transpose of a high dimensional array with specified order of axes

In [4]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)

arr1.transpose((1,0,2))
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


### swap axes

In [5]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


### change the shape of an array

In [6]:
# change the shape of an array and return a copy
arr.reshape((2,6))

array([[0.90971718, 0.63521059, 0.92260911, 0.01387662, 0.77175076,
        0.89323775],
       [0.76695081, 0.32906322, 0.34980711, 0.85417051, 0.6151757 ,
        0.02141629]])

In [7]:
# change the shape of an array in place
arr.resize((2,6))

### flatten an array

In [8]:
# return a copy
arr.flatten()    

array([0.90971718, 0.63521059, 0.92260911, 0.01387662, 0.77175076,
       0.89323775, 0.76695081, 0.32906322, 0.34980711, 0.85417051,
       0.6151757 , 0.02141629])

In [9]:
# return a view
# change any element in the view will change the initial array
arr.ravel()      

array([0.90971718, 0.63521059, 0.92260911, 0.01387662, 0.77175076,
       0.89323775, 0.76695081, 0.32906322, 0.34980711, 0.85417051,
       0.6151757 , 0.02141629])

### append elements to an array

In [10]:
arr = np.array([1,2,3])

In [11]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [12]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


### insert elements into an array

In [13]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [14]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])    
print(arr3)

[1 2 3 1 2 3]


### delete elements from an array

In [15]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [16]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


### copy an array

In [17]:
arr = np.array([1,2,3])

In [18]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)