# Data Structures 

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [2]:
import matplotlib.pyplot as plt

In [3]:
A = np.round(10*np.random.rand(5,4))

In [4]:
A

array([[6., 1., 2., 3.],
       [9., 5., 0., 2.],
       [3., 1., 5., 5.],
       [6., 8., 4., 4.],
       [2., 9., 1., 7.]])

In [5]:
A[1,2]

0.0

In [6]:
A[1,:]

array([9., 5., 0., 2.])

In [7]:
A[:,1]

array([1., 5., 1., 8., 9.])

In [8]:
A[1:3,2:4]

array([[0., 2.],
       [5., 5.]])

In [9]:
A

array([[6., 1., 2., 3.],
       [9., 5., 0., 2.],
       [3., 1., 5., 5.],
       [6., 8., 4., 4.],
       [2., 9., 1., 7.]])

In [10]:
A.T

array([[6., 9., 3., 6., 2.],
       [1., 5., 1., 8., 9.],
       [2., 0., 5., 4., 1.],
       [3., 2., 5., 4., 7.]])

In [11]:
import numpy.linalg as la

In [12]:
la.inv(np.random.rand(3,3))

array([[-0.82667816,  1.10484071,  0.2914726 ],
       [ 1.52965206,  0.65610159, -2.42924655],
       [ 0.18251448, -1.21070239,  3.52016996]])

In [13]:
A

array([[6., 1., 2., 3.],
       [9., 5., 0., 2.],
       [3., 1., 5., 5.],
       [6., 8., 4., 4.],
       [2., 9., 1., 7.]])

In [14]:
A.sort(axis=0)

In [15]:
A

array([[2., 1., 0., 2.],
       [3., 1., 1., 3.],
       [6., 5., 2., 4.],
       [6., 8., 4., 5.],
       [9., 9., 5., 7.]])

In [16]:
A.sort(axis=1)

In [17]:
A

array([[0., 1., 2., 2.],
       [1., 1., 3., 3.],
       [2., 4., 5., 6.],
       [4., 5., 6., 8.],
       [5., 7., 9., 9.]])

In [18]:
A = np.arange(100)

In [19]:
B = A[[3,5,6]]

In [20]:
B

array([3, 5, 6])

In [21]:
B[0] = -4

In [22]:
B

array([-4,  5,  6])

In [23]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
B = A[A<40]

In [25]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [26]:
B = A[(A<40) & (A>30)]

In [27]:
B

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [28]:
# &, and 
# |, or
# ~, not

In [29]:
A = np.round(10*np.random.rand(2,3))

In [30]:
A

array([[6., 8., 8.],
       [1., 6., 1.]])

In [31]:
A+3

array([[ 9., 11., 11.],
       [ 4.,  9.,  4.]])

In [32]:
A+(np.arange(2).reshape(2,1))

array([[6., 8., 8.],
       [2., 7., 2.]])

In [33]:
A

array([[6., 8., 8.],
       [1., 6., 1.]])

In [34]:
B = np.round(10*np.random.rand(2,2))

In [35]:
A

array([[6., 8., 8.],
       [1., 6., 1.]])

In [36]:
B

array([[4., 7.],
       [6., 7.]])

In [37]:
C = np.hstack((A,B))

In [38]:
C

array([[6., 8., 8., 4., 7.],
       [1., 6., 1., 6., 7.]])

In [39]:
A = np.random.permutation(np.arange(10))

In [40]:
A

array([9, 5, 2, 3, 4, 0, 1, 6, 8, 7])

In [41]:
A.sort()

In [42]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.sort(A)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
A.sort()

In [45]:
A = A[::-1]

In [46]:
A

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [47]:
A = np.array(["abc",'howare you','u765','13er'])

In [48]:
A.sort()

In [49]:
A

array(['13er', 'abc', 'howare you', 'u765'], dtype='<U10')

In [50]:
B = np.random.rand(1000000)
%timeit sum(B)
%timeit np.sum(B)  # B.sum()

223 ms ± 76.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.87 ms ± 569 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [51]:
def mySum(G):
    s = 0
    for x in G:
        s+=x
    return s

In [52]:
import pandas as pd

In [53]:
print(pd.__version__)

2.2.2


In [54]:
A = pd.Series([2,3,4,5],index=['a','b','c','d'])

In [55]:
type(A.values)

numpy.ndarray

In [56]:
type(A)

pandas.core.series.Series

In [57]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [58]:
A['a']

2

In [59]:
A['a':'c']

a    2
b    3
c    4
dtype: int64

In [60]:
grads_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grads = pd.Series(grads_dict)

In [61]:
grads.values

array([4. , 3.5, 3. , 2.5])

In [62]:
marks_dict = {'A':85,'B':75,'C':65,'D':55}
marks = pd.Series(marks_dict)

In [63]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [64]:
marks['A']

85

In [65]:
marks[0:2]

A    85
B    75
dtype: int64

In [66]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [67]:
grads

A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64

In [68]:
D = pd.DataFrame({'Marks':marks,'Grades':grads})

In [69]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [70]:
D.T

A     B     C     D
Marks   85.0  75.0  65.0  55.0
Grades   4.0   3.5   3.0   2.5

In [71]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [72]:
D.values

array([[85. ,  4. ],
       [75. ,  3.5],
       [65. ,  3. ],
       [55. ,  2.5]])

In [74]:
D.values[2,0]

65.0

In [75]:
D.columns

Index(['Marks', 'Grades'], dtype='object')

In [76]:
D['ScaledMarks'] = 100*(D['Marks']/90)


In [77]:
D

Marks  Grades  ScaledMarks
A     85     4.0    94.444444
B     75     3.5    83.333333
C     65     3.0    72.222222
D     55     2.5    61.111111

In [78]:
del D['ScaledMarks']

In [79]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [80]:
G = D[D['Marks']>70]

In [83]:
G

Marks  Grades
A     85     4.0
B     75     3.5

In [84]:
A = pd.DataFrame([{'a':1,'b':4},{'b':-3,'c':9}])

In [85]:
A

a  b    c
0  1.0  4  NaN
1  NaN -3  9.0

In [91]:
A.fillna(0)

a  b    c
0  1.0  4  0.0
1  0.0 -3  9.0

In [87]:
A.dropna?

Signature:
A.dropna(
    *,
    axis: 'Axis' = 0,
    how: 'AnyAll | lib.NoDefault' = <no_default>,
    thresh: 'int | lib.NoDefault' = <no_default>,
    subset: 'IndexLabel | None' = None,
    inplace: 'bool' = False,
    ignore_index: 'bool' = False,
) -> 'DataFrame | None'
Docstring:
Remove missing values.

See the :ref:`User Guide <missing_data>` for more on which values are
considered missing, and how to work with missing data.

Parameters
----------
axis : {0 or 'index', 1 or 'columns'}, default 0
    Determine if rows or columns which contain missing values are
    removed.

    * 0, or 'index' : Drop rows which contain missing values.
    * 1, or 'columns' : Drop columns which contain missing value.

    Only a single axis is allowed.

how : {'any', 'all'}, default 'any'
    Determine if row or column is removed from DataFrame, when we have
    at least one NA or all NA.

    * 'any' : If any NA values are present, drop that row or column.
    * 'all' : If all values are NA, dr

In [95]:
A = pd.Series(['a','b','c'],index=[1,3,5])

In [96]:
A

1    a
3    b
5    c
dtype: object

In [97]:
A[1]

'a'

In [101]:
A[1:3]

3    b
5    c
dtype: object

In [104]:
A.loc[1:3]

1    a
3    b
dtype: object

In [105]:
A.loc[1:3]

1    a
3    b
dtype: object