In [39]:
import numpy as np
import pandas as pd
import matplotlib as plt
import matplotlib.pyplot as plt

In [40]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])


In [41]:
A

array([[1, 2],
       [3, 4]])

In [42]:
B

array([[5, 6],
       [7, 8]])

In [43]:
C = np.hstack((A, B))


In [44]:
C

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [45]:
D = np.vstack((A,B))

In [46]:
D

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [47]:
A = np.random.permutation(np.arange(10))
A

array([6, 7, 1, 9, 2, 0, 4, 3, 8, 5])

In [48]:
A.sort()

In [49]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
B = np.random.permutation(np.arange(10))
B

array([9, 1, 2, 4, 8, 7, 5, 0, 6, 3])

In [51]:
np.sort(B)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
A = np.array(["abc",'howare you','u765','13er'])

In [53]:
A.sort()
A

array(['13er', 'abc', 'howare you', 'u765'], dtype='<U10')

In [54]:
B = np.random.rand(1000000)
%timeit sum(B)
%timeit np.sum(B)  # B.sum()

The slowest run took 4.34 times longer than the fastest. This could mean that an intermediate result is being cached.
185 ms ± 120 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
6.03 ms ± 2.15 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [55]:
import pandas as pd


In [56]:
A = pd.Series([2,3,4,5],index=['a','b','c','d'])

In [57]:
A

a    2
b    3
c    4
d    5
dtype: int64

In [58]:
type(A.values)

numpy.ndarray

In [59]:
type(A)

pandas.core.series.Series

In [60]:
A.index


Index(['a', 'b', 'c', 'd'], dtype='object')

In [61]:
A['a']

2

In [62]:
A['a':'c']

a    2
b    3
c    4
dtype: int64

In [63]:
grads_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grads = pd.Series(grads_dict)

In [64]:
grads

A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64

In [65]:
grads['A']

4.0

In [66]:
marks_dict = {'A':85,'B':75,'C':65,'D':55}
marks = pd.Series(marks_dict)

In [67]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [68]:
marks[0:2]

A    85
B    75
dtype: int64