In [28]:
import numpy as np

### Create an array from an iterable
Such as
- ```list```
- ```tuple```
- ```range``` iterator

Notice that not all iterables can be used to create a numpy array, such as ```set``` and ```dict```

In [29]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [30]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [31]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Create an array with specified data type

In [32]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)
print('Data Type: ' + str(arr.dtype))

[[1 2 3]
 [4 5 6]]
Data Type: int16


### Create an aray within specified range
```np.arange()``` method can be used to replace ```np.array(range())``` method

In [33]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


### Create an array of evenly spaced numbers within specified range
```np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False)``` has 5 parameters:
- ```start```: start number (inclusive)
- ```stop```: end number (inclusive unless ```endpoint``` set to ```False```)
- ```num_of_elements```: number of elements contained in the array
- ```endpoint```: boolean value representing whether the ```stop``` number is inclusive or not
- ```retstep```: boolean value representing whether to return the step size

In [34]:
arr, step_size = np.linspace(0, 5, 8, endpoint=False, retstep=True)
print(arr)
print('The step size is ' + str(step_size))

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]
The step size is 0.625


### Create an array of random values of given shape
```np.random.rand()``` method returns values in the range [0,1)

In [35]:
arr = np.random.rand(3, 3)
print(arr)

[[0.11035242 0.10904759 0.56525411]
 [0.49480046 0.27780364 0.77811952]
 [0.55504712 0.14892924 0.57545846]]


### Create an array of zeros of given shape 
- ```np.zeros()```: create array of all zeros in given shape
- ```np.zeros_like()```: create array of all zeros with the same shape and data type as the given input array

In [36]:
zeros = np.zeros((2,3))
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0. 0. 0.]
 [0. 0. 0.]]
Data Type: float64


In [37]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.complex64)
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
Data Type: complex64


### Create an array of ones of given shape 
- ```np.ones()```: create array of all ones in given shape
- ```np.ones_like()```: create array of all ones with the same shape and data type as the given input array

In [38]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [39]:
arr = [[1,2,3], [4,5,6]]
ones = np.ones_like(arr)
print(ones)
print('Data Type: ' + str(ones.dtype))

[[1 1 1]
 [1 1 1]]
Data Type: int32


### Create an empty array of given shape 
- ```np.empty()```: create array of empty values in given shape
- ```np.empty_like()```: create array of empty values with the same shape and data type as the given input array

Notice that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses.

In [40]:
empty = np.empty((5,5))
print(empty)

[[0.02557962 0.88694581 0.3307976  0.00447554 0.5139925 ]
 [0.066742   0.2997703  0.01467399 0.25915937 0.03719603]
 [0.23966703 0.97142845 0.77588741 0.46449959 0.72715591]
 [0.85403985 0.55301804 0.07222332 0.85507614 0.6346492 ]
 [0.65654417 0.40801695 0.68873775 0.72059413 0.08713049]]


Though all the values seem to be zero, they are uninitialized and can be set to any value. 
These are called garbage values

In [41]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
empty = np.empty_like(arr)
print(empty)
print('Data Type: ' + str(empty.dtype))

[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]
Data Type: int64


### Create an array of constant values of given shape  
- ```np.full()```: create array of constant values in given shape
- ```np.full_like()```: create array of constant values with the same shape and data type as the given input array

In [42]:
full = np.full((4,4), 5)
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [43]:
arr = np.array([[1,2], [3,4]], dtype=np.float64)
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

[[5. 5.]
 [5. 5.]]
Data Type: float64


### Create an array in a repetitive manner
- ```np.repeat(iterable, reps, axis=None)```: repeat each element by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions
    - ```axis```: which axis to repeat along, default is ```None``` which will flatten the input array and then repeat (0 - x-axis, 1 - y-axis)
- ```np.tile()```: repeat the whole array by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions, it can be a tuple to represent repetitions along x-axis and y-axis


      ```corresponding indices are matched while repeating```

In [44]:
# No axis specified, then flatten the input array first and repeat
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3)) 

[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [45]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=0)) 

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [46]:
# An example of repeating along y-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=1))    

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [47]:
# Repeat the whole array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [48]:
# Repeat along specified axes
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


### Create an identity matrix of given size
- ```np.eye(size, k=0)```: create an identity matrix of given size
    - ```size```: the size of the identity matrix
    - ```k```: the diagonal offset
- ```np.identity()```: same as ```np.eye()``` but does not carry parameters

In [49]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [50]:
# An example of diagonal offset
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [51]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Create an array with given values on the diagonal

In [52]:
arr = np.random.rand(5,5)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.40746692 0.36762978 0.3630847  0.45243037 0.06038448]
 [0.35374517 0.55725391 0.78919254 0.94448473 0.47054158]
 [0.40011212 0.15155697 0.20971721 0.09211403 0.56915655]
 [0.29039242 0.67592889 0.03845245 0.07759463 0.69951609]
 [0.29883444 0.40286117 0.05516124 0.37515558 0.31580396]]
Values on the diagonal: [0.40746692 0.55725391 0.20971721 0.07759463 0.31580396]


In [53]:
# Not necessarily to be a square matrix
arr = np.random.rand(10,3)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.79874801 0.85390298 0.75114453]
 [0.20928071 0.75284941 0.50100364]
 [0.16319478 0.08387564 0.82327453]
 [0.16097518 0.39603372 0.57779103]
 [0.61065416 0.46391916 0.29638074]
 [0.90399544 0.56800961 0.45455919]
 [0.33833361 0.11760635 0.7864497 ]
 [0.63814261 0.37198756 0.71670677]
 [0.37517777 0.75423519 0.72446222]
 [0.6414457  0.75271265 0.82902297]]
Values on the diagonal: [0.79874801 0.75284941 0.82327453]


In [54]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
